all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
all_joints_names:
- F_reye
- F_leye
- F_rch
- F_lch
- F_cch
- F_ge
- M_reye
- M_leye
- M_rch
- M_lch
- M_cch
- M_ge
alpha_r: 0.02
batch_size: 1
clahe: true
claheratio: 0.1
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_det_cop_optoOct22\det_cop_opto_yama95shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: C:\Users\nokai\anaconda3\envs\DLC-GPU2\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_det_cop_optoOct22\Documentation_data-det_cop_opto_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 12
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: C:\Users\nokai\Desktop\Yamanouchi\det_cop_opto-yama-2021-11-11
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
